import "./globals.css";

export const metadata = {
  title: "Colors Drop",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
