import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/Navbar";
import RestoreScroll from "@/components/common/RestoreScroll";

export const metadata = {
  title: "Colors Drop",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function AssetsRootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <RestoreScroll />
        <div id="modal-root" />
        {children}
        {modal}
        <Footer />
      </body>
    </html>
  );
}
